// ============================================================
//  NBCOT PREP — Question Bank & Domain Data
//  75 clinically accurate NBCOT-style questions
// ============================================================

const DOMAINS = [
  { id: 'evaluation',     label: 'Evaluation & Assessment',       color: '#6366F1', icon: '🔍' },
  { id: 'foundations',    label: 'Foundational Knowledge',        color: '#0EA5E9', icon: '📚' },
  { id: 'intervention',   label: 'Intervention',                  color: '#10B981', icon: '🏥' },
  { id: 'pediatrics',     label: 'Pediatric Practice',            color: '#F59E0B', icon: '🧒' },
  { id: 'mental_health',  label: 'Mental Health',                 color: '#8B5CF6', icon: '🧠' },
  { id: 'professional',   label: 'Professional Practice',         color: '#F43F5E', icon: '⚖️' },
];

const QUESTIONS = [

  // ─────────────────────────────────────────────
  //  EVALUATION & ASSESSMENT  (Q001–Q015)
  // ─────────────────────────────────────────────
  {
    id: 'q001',
    domain: 'evaluation',
    subdomain: 'Standardized Tools',
    stem: 'A client with a stroke scores a "3" on the Functional Independence Measure (FIM) for dressing. Which of the following best describes this level of function?',
    type: 'mcq',
    options: [
      'A) Complete independence — client performs without modification',
      'B) Modified independence — client uses an assistive device',
      'C) Moderate assistance — client performs 50–74% of the task',
      'D) Moderate dependence — helper does 50–74% of the task',
    ],
    correct: 3,
    rationale: 'FIM level 3 = Moderate Assistance, meaning the client provides 50–74% of the effort, but a helper provides 25–49%. Scores range from 1 (Total Dependence) to 7 (Complete Independence). A score of 5 reflects Supervision only; 6 is Modified Independence with a device.',
    difficulty: 2,
    tags: ['FIM', 'stroke', 'ADL', 'scoring'],
  },
  {
    id: 'q002',
    domain: 'evaluation',
    subdomain: 'Client-Centered Assessment',
    stem: 'An OT uses the Canadian Occupational Performance Measure (COPM) during an initial evaluation. What is the PRIMARY purpose of this tool?',
    type: 'mcq',
    options: [
      'A) To measure grip strength and pinch strength bilaterally',
      'B) To detect cognitive impairment that may affect daily function',
      'C) To identify the client\'s perceived occupational performance problems and satisfaction',
      'D) To classify disability severity according to the International Classification of Functioning',
    ],
    correct: 2,
    rationale: 'The COPM is a semi-structured interview that identifies problems in daily occupational performance as prioritized by the client. It measures the client\'s self-perception of performance and satisfaction across self-care, productivity, and leisure. It is client-centered, not clinician-rated.',
    difficulty: 1,
    tags: ['COPM', 'evaluation', 'client-centered', 'occupational performance'],
  },
  {
    id: 'q003',
    domain: 'evaluation',
    subdomain: 'Motor Assessment',
    stem: 'During a manual muscle test (MMT), the OT places the client\'s wrist extensor muscle in a gravity-eliminated position and the client moves through partial range of motion. What MMT grade does this correspond to?',
    type: 'mcq',
    options: [
      'A) Grade 1 (Trace)',
      'B) Grade 2- (Poor Minus)',
      'C) Grade 2 (Poor)',
      'D) Grade 3- (Fair Minus)',
    ],
    correct: 1,
    rationale: 'Grade 2- (Poor Minus) indicates partial ROM in a gravity-eliminated position. Grade 2 (Poor) = full ROM in gravity-eliminated. Grade 1 (Trace) = visible/palpable contraction without movement. Grade 3 (Fair) = full ROM against gravity with no added resistance.',
    difficulty: 2,
    tags: ['MMT', 'manual muscle test', 'motor assessment', 'grading'],
  },
  {
    id: 'q004',
    domain: 'evaluation',
    subdomain: 'Upper Extremity Assessment',
    stem: 'When using a Jamar dynamometer to measure grip strength, what is the standard testing position for the elbow?',
    type: 'mcq',
    options: [
      'A) Fully extended at 0°',
      'B) Flexed at 90° with forearm in neutral rotation',
      'C) Flexed at 45° with forearm supinated',
      'D) Flexed at 90° with forearm fully pronated',
    ],
    correct: 1,
    rationale: 'The standardized Jamar dynamometer grip strength test is conducted with the elbow flexed to 90°, forearm in neutral rotation (thumb up), shoulder adducted, and wrist in neutral position. This position is consistent with American Society of Hand Therapists (ASHT) guidelines and allows meaningful comparison to normative data.',
    difficulty: 2,
    tags: ['grip strength', 'Jamar', 'hand therapy', 'upper extremity'],
  },
  {
    id: 'q005',
    domain: 'evaluation',
    subdomain: 'Cognitive Screening',
    stem: 'A client scores 24/30 on the Montreal Cognitive Assessment (MoCA). How should the OT interpret this score?',
    type: 'mcq',
    options: [
      'A) Normal cognition — no further evaluation needed',
      'B) Mild cognitive impairment — score is below the cutoff of 26',
      'C) Moderate dementia — referral to neuropsychology is urgent',
      'D) The score is invalid without adjusting for education level first',
    ],
    correct: 1,
    rationale: 'The MoCA cutoff for normal cognition is ≥26/30. A score of 24 falls below this threshold and is consistent with mild cognitive impairment (MCI). Scores are adjusted +1 point for ≤12 years of education. The MoCA is sensitive to MCI and early Alzheimer\'s. The OT should document findings and consider further evaluation of functional cognition.',
    difficulty: 2,
    tags: ['MoCA', 'cognitive screening', 'dementia', 'MCI'],
  },
  {
    id: 'q006',
    domain: 'evaluation',
    subdomain: 'Functional Performance',
    stem: 'The Assessment of Motor and Process Skills (AMPS) differs from most other OT assessments because it:',
    type: 'mcq',
    options: [
      'A) Uses caregiver report rather than direct observation',
      'B) Evaluates performance quality within naturalistic, chosen tasks',
      'C) Measures only the physical components of ADL performance',
      'D) Is specifically designed for clients with neurological conditions',
    ],
    correct: 1,
    rationale: 'The AMPS is unique in that it measures the quality of ADL task performance through observation of chosen, familiar tasks in a naturalistic context. It samples 16 motor and 20 process skill items, providing a Rasch-calibrated measurement of task effort, efficiency, safety, and independence. It is not diagnosis-specific and does not rely on caregiver report.',
    difficulty: 2,
    tags: ['AMPS', 'performance quality', 'functional assessment', 'Rasch'],
  },
  {
    id: 'q007',
    domain: 'evaluation',
    subdomain: 'Sensory Assessment',
    stem: 'An OT evaluates a 7-year-old using the Sensory Processing Measure (SPM). Which environment-specific form would be completed by the classroom teacher?',
    type: 'mcq',
    options: [
      'A) The Home Form',
      'B) The Main Form',
      'C) The School Form',
      'D) The Classroom Form',
    ],
    correct: 3,
    rationale: 'The SPM has multiple forms: the Home Form (completed by a parent/guardian), the Main Classroom Form (completed by the primary teacher), and Environment Forms for School Environments (art, music, PE). The teacher would complete the Main Classroom Form. The SPM assesses sensory processing in context across social participation, vision, hearing, touch, body awareness, balance, and planning/ideas.',
    difficulty: 2,
    tags: ['SPM', 'sensory processing', 'pediatrics', 'teacher report'],
  },
  {
    id: 'q008',
    domain: 'evaluation',
    subdomain: 'Pediatric Assessment',
    stem: 'The Pediatric Evaluation of Disability Inventory – Computer Adaptive Test (PEDI-CAT) measures function in children across which domains?',
    type: 'mcq',
    options: [
      'A) Cognition, language, motor, and social-emotional',
      'B) Daily activities, mobility, social/cognitive, and responsibility',
      'C) Self-care, play, school function, and peer interaction',
      'D) Gross motor, fine motor, communication, and adaptive behavior',
    ],
    correct: 1,
    rationale: 'The PEDI-CAT measures functional capability and performance across four domains: Daily Activities, Mobility, Social/Cognitive, and Responsibility (the degree to which the caregiver versus the child manages tasks). It is norm-referenced and can be used from birth through young adulthood. The Responsibility domain is unique to the PEDI-CAT/PEDI for tracking caregiver involvement.',
    difficulty: 2,
    tags: ['PEDI-CAT', 'pediatric', 'functional assessment', 'disability'],
  },
  {
    id: 'q009',
    domain: 'evaluation',
    subdomain: 'Cognitive Assessment',
    stem: 'The Allen Cognitive Level Screen (ACLS) is based on which theoretical framework?',
    type: 'mcq',
    options: [
      'A) Model of Human Occupation (MOHO)',
      'B) Cognitive Disabilities Model (Allen)',
      'C) Neurodevelopmental Treatment (NDT)',
      'D) Person–Environment–Occupation (PEO) Model',
    ],
    correct: 1,
    rationale: 'The ACLS is grounded in Allen\'s Cognitive Disabilities Model, which proposes that cognitive disabilities caused by neurobiological disorders limit functional performance. The screen uses leather-lacing tasks at increasing complexity to estimate Allen Cognitive Levels (1–6), guiding appropriate activity levels and caregiver support. It does NOT arise from MOHO or NDT frameworks.',
    difficulty: 1,
    tags: ['Allen', 'cognitive disabilities', 'ACLS', 'mental health'],
  },
  {
    id: 'q010',
    domain: 'evaluation',
    subdomain: 'Upper Extremity Assessment',
    stem: 'An OT uses the Nine-Hole Peg Test (NHPT) with a client who has multiple sclerosis. What functional construct does this test primarily measure?',
    type: 'mcq',
    options: [
      'A) Grip strength',
      'B) Fine motor dexterity and speed',
      'C) Pinch strength',
      'D) Hand–eye coordination during bimanual tasks',
    ],
    correct: 1,
    rationale: 'The Nine-Hole Peg Test measures finger dexterity and fine motor speed. The client places and removes 9 pegs from a pegboard as quickly as possible; the score is time in seconds. It is a standardized, reliable measure of upper extremity fine motor function commonly used in MS, stroke, and TBI populations. It does not directly measure grip or pinch strength.',
    difficulty: 1,
    tags: ['NHPT', 'fine motor', 'dexterity', 'multiple sclerosis', 'upper extremity'],
  },
  {
    id: 'q011',
    domain: 'evaluation',
    subdomain: 'Community Living',
    stem: 'The Kohlman Evaluation of Living Skills (KELS) assesses a client\'s ability to function in which setting?',
    type: 'mcq',
    options: [
      'A) Inpatient psychiatric unit',
      'B) Independent community living',
      'C) Skilled nursing facility',
      'D) Supported employment',
    ],
    correct: 1,
    rationale: 'The KELS evaluates functional skills required for independent community living. It assesses 17 tasks in 5 areas: self-care, safety and health, money management, transportation and telephone, and work and leisure. It is frequently used in mental health settings to determine a client\'s capacity for safe community living or the level of support needed.',
    difficulty: 2,
    tags: ['KELS', 'community living', 'IADL', 'mental health', 'independent living'],
  },
  {
    id: 'q012',
    domain: 'evaluation',
    subdomain: 'Standardized ADL Tools',
    stem: 'The Barthel Index scores activities of daily living. A client who requires MINIMAL assistance (less than 50% help) with bathing would receive which score for that item?',
    type: 'mcq',
    options: [
      'A) 0 — Dependent',
      'B) 5 — Needs help',
      'C) 10 — Independent',
      'D) 15 — Independent with equipment',
    ],
    correct: 0,
    rationale: 'On the Barthel Index, Bathing is scored 0 (dependent/needs help) or 5 (independent, including getting in/out of tub). Any need for assistance results in 0 for this item. The Barthel Index uses 0/5/10/15 increments depending on the activity. It is commonly used in rehabilitation and stroke care to measure functional independence.',
    difficulty: 3,
    tags: ['Barthel', 'ADL', 'scoring', 'functional independence'],
  },
  {
    id: 'q013',
    domain: 'evaluation',
    subdomain: 'Range of Motion',
    stem: 'When measuring passive range of motion (PROM) of wrist extension using a goniometer, where is the axis (fulcrum) placed?',
    type: 'mcq',
    options: [
      'A) Over the radial styloid',
      'B) Over the lateral epicondyle of the humerus',
      'C) Over the ulnar styloid',
      'D) Over the lateral aspect of the wrist, aligned with the capitate',
    ],
    correct: 3,
    rationale: 'For wrist extension/flexion, the goniometer axis is placed over the lateral aspect of the wrist, in line with the capitate bone. The stationary arm aligns with the lateral midline of the radius; the moving arm aligns with the lateral midline of the fifth metacarpal. The ulnar styloid and radial styloid are landmarks used for other measurements (e.g., forearm rotation, ulnar/radial deviation).',
    difficulty: 3,
    tags: ['goniometry', 'ROM', 'wrist', 'hand therapy'],
  },
  {
    id: 'q014',
    domain: 'evaluation',
    subdomain: 'Goal Setting',
    stem: 'Goal Attainment Scaling (GAS) is used in OT to:',
    type: 'mcq',
    options: [
      'A) Rank clients by severity of disability on a standardized scale',
      'B) Set individualized, weighted outcome goals and measure attainment',
      'C) Calculate a predicted discharge date based on admission data',
      'D) Monitor vital signs during exercise to ensure safety',
    ],
    correct: 1,
    rationale: 'GAS is a client-centered method for setting individualized rehabilitation goals and measuring the degree to which they are achieved. Each goal is assigned a 5-point scale from –2 (much less than expected) to +2 (much better than expected), with 0 being the expected outcome. Goals are weighted by importance and difficulty, and a composite T-score can be calculated. It is particularly valuable for capturing meaningful outcomes not measured by standardized tools.',
    difficulty: 2,
    tags: ['GAS', 'goal setting', 'outcome measurement', 'person-centered'],
  },
  {
    id: 'q015',
    domain: 'evaluation',
    subdomain: 'Occupational Profile',
    stem: 'According to the OTPF-4, what is the PRIMARY purpose of the occupational profile?',
    type: 'mcq',
    options: [
      'A) To determine a clinical diagnosis for billing and documentation purposes',
      'B) To understand the client\'s occupational history, experiences, patterns, and goals',
      'C) To measure baseline functional performance using standardized assessments',
      'D) To identify the evidence base that will guide the intervention plan',
    ],
    correct: 1,
    rationale: 'The OTPF-4 describes the occupational profile as a summary of the client\'s occupational history, experiences, patterns of daily living, interests, values, needs, and priorities. It is gathered through interview and establishes the foundation for all subsequent evaluation and intervention. Standardized testing belongs to the analysis of occupational performance, not the profile.',
    difficulty: 1,
    tags: ['OTPF', 'occupational profile', 'evaluation process', 'client history'],
  },

  // ─────────────────────────────────────────────
  //  FOUNDATIONAL KNOWLEDGE  (Q016–Q030)
  // ─────────────────────────────────────────────
  {
    id: 'q016',
    domain: 'foundations',
    subdomain: 'Models of Practice',
    stem: 'In the Model of Human Occupation (MOHO), the concept of "volition" refers to:',
    type: 'mcq',
    options: [
      'A) The physical and cognitive capacity to perform occupations',
      'B) The motivation, values, and personal causation that drive occupational choices',
      'C) The roles and habits that organize daily routines',
      'D) The physical, social, and cultural environment that supports or hinders performance',
    ],
    correct: 1,
    rationale: 'In MOHO (Kielhofner), the human system is composed of Volition (motivation — values, interests, personal causation), Habituation (roles and habits), and Performance Capacity (physical/mental abilities). Volition reflects the tendency to engage in occupation and the personal meaning ascribed to activities. The environment is a separate construct in MOHO that interacts with human system components.',
    difficulty: 2,
    tags: ['MOHO', 'volition', 'Kielhofner', 'theory'],
  },
  {
    id: 'q017',
    domain: 'foundations',
    subdomain: 'OT Practice Framework',
    stem: 'Which of the following is classified as an "area of occupation" in the Occupational Therapy Practice Framework, 4th Edition (OTPF-4)?',
    type: 'mcq',
    options: [
      'A) Sensory processing',
      'B) Role competence',
      'C) Rest and sleep',
      'D) Cognitive function',
    ],
    correct: 2,
    rationale: 'The OTPF-4 identifies eight areas of occupation: Activities of Daily Living (ADL), Instrumental ADL, Health Management, Rest and Sleep, Education, Work, Play, Leisure, and Social Participation. Sensory processing and cognitive function are client factors or performance skills. Role competence is a component of well-being/occupational balance, not an area of occupation.',
    difficulty: 1,
    tags: ['OTPF', 'areas of occupation', 'rest and sleep', 'framework'],
  },
  {
    id: 'q018',
    domain: 'foundations',
    subdomain: 'Models of Practice',
    stem: 'An OT using the Person–Environment–Occupation (PEO) Model focuses intervention on maximizing "occupational performance," which is best described as:',
    type: 'mcq',
    options: [
      'A) The client\'s level of physical independence in self-care tasks',
      'B) The dynamic fit among person, environment, and occupation over time',
      'C) The number of ADL tasks completed without caregiver assistance',
      'D) The client\'s intrinsic motivation to participate in meaningful activities',
    ],
    correct: 1,
    rationale: 'In the PEO Model (Law et al., 1996), occupational performance is the result of the transactive fit among Person (skills, abilities, roles), Environment (physical, social, cultural, institutional), and Occupation (tasks, activities). Optimizing performance involves improving the fit across all three components, not just physical independence. Intervention may target any one or combination of the three elements.',
    difficulty: 2,
    tags: ['PEO', 'occupational performance', 'model', 'theory'],
  },
  {
    id: 'q019',
    domain: 'foundations',
    subdomain: 'Frames of Reference',
    stem: 'The Biomechanical Frame of Reference is MOST appropriate for a client who:',
    type: 'mcq',
    options: [
      'A) Has intact central nervous system function and a peripheral musculoskeletal impairment',
      'B) Shows difficulty processing sensory information due to autism spectrum disorder',
      'C) Demonstrates poor role identity following a psychiatric hospitalization',
      'D) Has upper motor neuron damage causing spasticity after a stroke',
    ],
    correct: 0,
    rationale: 'The Biomechanical Frame of Reference addresses deficits in ROM, strength, and endurance and assumes an intact CNS. It is most appropriate when the cause is peripheral (e.g., fractures, orthopedic surgeries, peripheral nerve injuries, burns). For upper motor neuron conditions like stroke with spasticity, NDT or neurodevelopmental approaches are more appropriate because the biomechanical frame cannot address abnormal tone or motor control.',
    difficulty: 2,
    tags: ['biomechanical', 'frame of reference', 'CNS', 'peripheral', 'orthopedic'],
  },
  {
    id: 'q020',
    domain: 'foundations',
    subdomain: 'Frames of Reference',
    stem: 'Neurodevelopmental Treatment (NDT/Bobath) for a child with cerebral palsy is primarily aimed at:',
    type: 'mcq',
    options: [
      'A) Strengthening weak muscles through resistive exercise',
      'B) Inhibiting abnormal tone and facilitating normal movement patterns',
      'C) Teaching compensatory techniques to bypass motor deficits',
      'D) Building cognitive strategies to plan and sequence movements',
    ],
    correct: 1,
    rationale: 'NDT (Bobath approach) focuses on inhibiting abnormal reflex patterns and tonal abnormalities while facilitating normal automatic movements and postural reactions. Key concepts include handling techniques, key points of control, and movement preparation. Unlike compensatory approaches, NDT aims to improve underlying motor quality. It is widely used for children with cerebral palsy and adults post-stroke.',
    difficulty: 2,
    tags: ['NDT', 'Bobath', 'cerebral palsy', 'tone', 'motor control'],
  },
  {
    id: 'q021',
    domain: 'foundations',
    subdomain: 'Sensory Theory',
    stem: 'Sensory Integration Theory (Ayres) proposes that the brain\'s ability to organize and interpret sensory information from the body and environment to produce adaptive responses is called:',
    type: 'mcq',
    options: [
      'A) Sensory modulation',
      'B) Sensory integration',
      'C) Praxis',
      'D) Tactile discrimination',
    ],
    correct: 1,
    rationale: 'Ayres defined sensory integration as the neurological process that organizes sensations from one\'s own body and from the environment to make it possible to use the body effectively in the environment. Sensory modulation refers specifically to regulating the degree of response to sensory input. Praxis is the ability to ideate, plan, and execute novel motor tasks. Tactile discrimination is one component under the sensory integration umbrella.',
    difficulty: 1,
    tags: ['sensory integration', 'Ayres', 'theory', 'definitions'],
  },
  {
    id: 'q022',
    domain: 'foundations',
    subdomain: 'Activity Analysis',
    stem: 'An OT performs an activity analysis of knitting. Which of the following represents a "process skill" as defined in the OTPF-4?',
    type: 'mcq',
    options: [
      'A) Manipulates yarn with adequate grip strength',
      'B) Sequences the row pattern without losing track of steps',
      'C) Maintains upright seated posture throughout the task',
      'D) Coordinates bilateral hand movements smoothly',
    ],
    correct: 1,
    rationale: 'In the OTPF-4, process skills refer to actions used in managing and modifying actions en route to task completion — including temporal organization (sequencing, initiating, terminating), organizing space and objects, and adapting. Grip strength is a motor skill; seated posture is a motor/performance skill; bilateral coordination is also a motor skill. Sequencing the pattern is a process skill.',
    difficulty: 2,
    tags: ['activity analysis', 'process skills', 'OTPF', 'performance skills'],
  },
  {
    id: 'q023',
    domain: 'foundations',
    subdomain: 'Performance Patterns',
    stem: 'A client who performs morning routines automatically in the same order each day without conscious thought is demonstrating a(n):',
    type: 'mcq',
    options: [
      'A) Role',
      'B) Habit',
      'C) Routine',
      'D) Ritual',
    ],
    correct: 1,
    rationale: 'Habits are automatic behaviors acquired through repetition that allow actions to be performed without deliberate effort. Routines are established sequences of occupations that provide structure and meaning to daily life. Roles are sets of behaviors expected by society and shaped by culture. Rituals are symbolic actions with spiritual, cultural, or social meaning. The automatic, repetitive nature of the morning sequence describes a habit.',
    difficulty: 1,
    tags: ['habits', 'routines', 'performance patterns', 'OTPF'],
  },
  {
    id: 'q024',
    domain: 'foundations',
    subdomain: 'Intervention Approaches',
    stem: 'An OT working in a community falls prevention program designs a balance exercise class for well older adults. This intervention approach is BEST described as:',
    type: 'mcq',
    options: [
      'A) Establish/Restore — building skills that have been lost',
      'B) Maintain — preserving current performance capacity',
      'C) Create/Promote — enhancing performance without assuming deficits',
      'D) Modify — changing tasks or environment to support performance',
    ],
    correct: 2,
    rationale: 'The Create/Promote approach is used with individuals or populations who do not have identified deficits but can benefit from enriched environments and activities that enhance participation. A falls prevention class for healthy older adults is health promotion — creating opportunity to build resilience before dysfunction occurs. Establish/Restore addresses existing deficits; Maintain prevents decline in those already at risk; Modify involves compensatory adaptations.',
    difficulty: 2,
    tags: ['intervention approaches', 'health promotion', 'create/promote', 'OTPF'],
  },
  {
    id: 'q025',
    domain: 'foundations',
    subdomain: 'Classification Systems',
    stem: 'The International Classification of Functioning, Disability and Health (WHO-ICF) concept of "participation restrictions" is most analogous to which OTPF-4 construct?',
    type: 'mcq',
    options: [
      'A) Client factors',
      'B) Performance skills',
      'C) Areas of occupation',
      'D) Activity demands',
    ],
    correct: 2,
    rationale: 'The ICF framework includes Body Functions/Structures, Activity (executing tasks), and Participation (involvement in life situations). Participation restrictions align most closely with OTPF-4\'s "areas of occupation" — the life areas in which the client engages (ADL, work, leisure, etc.). ICF "activity limitations" correspond more to OTPF "performance skills." ICF "body functions" align with OTPF "client factors."',
    difficulty: 3,
    tags: ['WHO-ICF', 'OTPF', 'participation', 'classification', 'framework'],
  },
  {
    id: 'q026',
    domain: 'foundations',
    subdomain: 'Pediatric Development',
    stem: 'At what typical developmental age does a child begin to use a mature, 3-jaw chuck (tripod) grasp to hold a crayon?',
    type: 'mcq',
    options: [
      'A) 12–18 months',
      'B) 2–2.5 years',
      'C) 3–4 years',
      'D) 5–6 years',
    ],
    correct: 2,
    rationale: 'A mature tripod (3-jaw chuck) grasp — thumb, index, and middle fingers working together with object stability — typically emerges around 3–4 years of age. At 12–18 months, children use a primitive whole-hand radial or palmar grasp. By age 2–2.5, children transition to digital pronate or static tripod. True dynamic tripod (with in-hand movement) emerges around 4.5–5 years.',
    difficulty: 2,
    tags: ['developmental milestones', 'grasp development', 'pediatrics', 'fine motor'],
  },
  {
    id: 'q027',
    domain: 'foundations',
    subdomain: 'Group Process',
    stem: 'In Mosey\'s developmental group taxonomy, a "cooperative group" is characterized by:',
    type: 'mcq',
    options: [
      'A) Members working on parallel tasks with minimal interaction',
      'B) Short-term sharing of tasks with some awareness of group norms',
      'C) Members jointly pursuing a shared goal with mutual give-and-take',
      'D) A therapist-directed group focused on a single project outcome',
    ],
    correct: 2,
    rationale: 'Mosey\'s five developmental group levels (in order): Parallel, Project, Egocentric-Cooperative, Cooperative, and Mature. The Cooperative group (level 4) involves members with insight into their own and others\' needs, pursuing a shared interaction goal with genuine give-and-take. Members can subordinate self-interest for the group\'s benefit. Parallel groups (level 1) work side-by-side with minimal interaction; Project groups (level 2) share short-term tasks.',
    difficulty: 3,
    tags: ['Mosey', 'group taxonomy', 'cooperative group', 'mental health'],
  },
  {
    id: 'q028',
    domain: 'foundations',
    subdomain: 'Frames of Reference',
    stem: 'The Task-Oriented Approach (Horak/Bass-Haugen) to motor rehabilitation assumes that movement emerges from the interaction of:',
    type: 'mcq',
    options: [
      'A) Muscle strength, joint flexibility, and proprioceptive accuracy',
      'B) The individual, the task, and the environment',
      'C) Reflexes, postural tone, and cortical control',
      'D) Volition, habituation, and performance capacity',
    ],
    correct: 1,
    rationale: 'The Task-Oriented Approach is based on systems theory of motor control (Bernstein, Shumway-Cook). It proposes that functional movement emerges from the dynamic interaction of the person (cognitive, physical), the task demands (nature of the goal), and the environment (surfaces, objects, context). Therapy focuses on task-specific practice in relevant environments. Reflexes and postural tone belong to older hierarchical motor control theories.',
    difficulty: 2,
    tags: ['task-oriented approach', 'motor control', 'systems theory', 'frame of reference'],
  },
  {
    id: 'q029',
    domain: 'foundations',
    subdomain: 'Anatomy',
    stem: 'Intrinsic muscles of the hand that are responsible for abduction of the index, middle, ring, and little fingers are the:',
    type: 'mcq',
    options: [
      'A) Lumbricals',
      'B) Palmar interossei',
      'C) Dorsal interossei',
      'D) Hypothenar muscles',
    ],
    correct: 2,
    rationale: 'The dorsal interossei (4 muscles) abduct the fingers away from the middle (long) digit, which is the axis of the hand (DAB — Dorsal ABduct). The palmar interossei (3–4 muscles) adduct the fingers toward the middle digit (PAD — Palmar ADduct). The lumbricals flex the MCP while extending the IP joints. The hypothenar muscles control the little finger (opposition, abduction, flexion).',
    difficulty: 2,
    tags: ['anatomy', 'intrinsic muscles', 'hand', 'interossei'],
  },
  {
    id: 'q030',
    domain: 'foundations',
    subdomain: 'Neuroanatomy',
    stem: 'A client with a C6 complete spinal cord injury would be expected to have INTACT strength in which upper extremity muscle group?',
    type: 'mcq',
    options: [
      'A) Finger flexors and extensors',
      'B) Wrist extensors',
      'C) Triceps',
      'D) Intrinsic hand muscles',
    ],
    correct: 1,
    rationale: 'C6 innervates the wrist extensors (extensor carpi radialis longus and brevis). A C6 complete SCI means everything at and above C6 is intact. C6 key muscles: wrist extensors. C7 = wrist flexors and finger extensors (triceps). C8 = finger flexors. T1 = intrinsic hand muscles. A C6 client can use tenodesis (passive finger flexion from wrist extension via the long finger flexors) for functional grasp.',
    difficulty: 2,
    tags: ['spinal cord injury', 'SCI', 'C6', 'innervation', 'neuroanatomy'],
  },

  // ─────────────────────────────────────────────
  //  INTERVENTION — Physical Dysfunction  (Q031–Q055)
  // ─────────────────────────────────────────────
  {
    id: 'q031',
    domain: 'intervention',
    subdomain: 'Neurological Rehabilitation',
    stem: 'An OT is working with a client who had a left hemispheric stroke and has right upper extremity weakness. The client\'s hemiplegic arm is at risk for subluxation of the glenohumeral joint. Which intervention BEST prevents this complication?',
    type: 'mcq',
    options: [
      'A) Applying a shoulder sling whenever the client is ambulatory',
      'B) Performing passive ROM exercises in full shoulder elevation daily',
      'C) Educating staff and caregivers on correct handling, positioning, and supported transfers',
      'D) Applying a figure-of-8 elastic bandage wrap to the shoulder',
    ],
    correct: 2,
    rationale: 'Shoulder subluxation post-stroke results from weak rotator cuff muscles, primarily supraspinatus and deltoid, allowing the humeral head to fall inferiorly. The primary prevention strategy is correct positioning and handling — supporting the arm when upright (lap tray, arm trough), avoiding traction on the shoulder during transfers, and training all staff and family. Slings are controversial (limited evidence, potential for learned non-use); aggressive ROM into full elevation may cause impingement over deltoid tears.',
    difficulty: 2,
    tags: ['stroke', 'shoulder subluxation', 'hemiplegia', 'positioning'],
  },
  {
    id: 'q032',
    domain: 'intervention',
    subdomain: 'Orthotic Intervention',
    stem: 'A resting hand orthosis (resting pan splint) is typically fabricated to position the wrist, fingers, and thumb in which functional position?',
    type: 'mcq',
    options: [
      'A) Wrist 0°, fingers full extension, thumb in palmar abduction',
      'B) Wrist 20–30° extension, MCPs 45–60° flexion, PIPs/DIPs slight flexion, thumb in partial opposition',
      'C) Wrist neutral, fingers in fist position, thumb opposed to ring finger',
      'D) Wrist 30° flexion, fingers in intrinsic plus position, thumb adducted',
    ],
    correct: 1,
    rationale: 'A resting hand orthosis places the wrist in 20–30° extension, MCP joints in 45–60° flexion, PIP and DIP joints in slight flexion (10–20°), and the thumb in partial abduction/opposition midway between palmar and radial abduction. This maintains the transverse and longitudinal arches and prevents soft tissue contractures at rest. This is often worn at night for conditions such as RA, spasticity, or after burns.',
    difficulty: 2,
    tags: ['orthotic', 'resting hand splint', 'positioning', 'hand therapy'],
  },
  {
    id: 'q033',
    domain: 'intervention',
    subdomain: 'SCI Rehabilitation',
    stem: 'An OT is training a client with a C6 tetraplegic complete SCI to use a tenodesis grasp. Tenodesis is best described as:',
    type: 'mcq',
    options: [
      'A) A powered splint that opens and closes with shoulder movement',
      'B) Passive finger flexion caused by active wrist extension, allowing functional grasp',
      'C) Surgical tendon transfer that restores active grip in the thumb and fingers',
      'D) A cuff-and-loop splint that holds objects without hand grip',
    ],
    correct: 1,
    rationale: 'Tenodesis grasp exploits the natural biomechanical relationship between wrist position and finger length: as the wrist extends (C6 function), finger flexors (which cross the wrist) become taut, passively flexing the fingers into a functional lateral pinch or grasp. When the wrist drops into flexion, fingers open. Training focuses on strengthening wrist extensors and preventing overstretching of finger flexors. It is a natural compensatory function of an intact finger tendon system.',
    difficulty: 2,
    tags: ['tenodesis', 'SCI', 'C6', 'grasp', 'tetraplegic'],
  },
  {
    id: 'q034',
    domain: 'intervention',
    subdomain: 'Burns',
    stem: 'A client with a circumferential burn to the hands is in the acute phase. Which positioning strategy is MOST important to prevent contracture?',
    type: 'mcq',
    options: [
      'A) Position the hand in a tight fist to maintain skin length on the dorsum',
      'B) Elevate hands above heart level and position in "safe position" — wrist extended, MCPs flexed, IPs extended, thumb abducted',
      'C) Keep the hand in a neutral position at heart level to minimize edema',
      'D) Apply a palmar gutter splint with the wrist in 30° flexion',
    ],
    correct: 1,
    rationale: 'The "safe position" (or "Edinburgh position") for burn hand splinting prevents the most disabling contractures: wrist 20–30° extension, MCP 70–90° flexion (to maintain collateral ligament length), PIP and DIP joints in full extension (to prevent flexion contractures), and thumb in abduction/opposition. Elevation reduces edema. Positioning the hand in flexion causes IP flexion contractures; a tight fist closes the web spaces and shortens skin.',
    difficulty: 2,
    tags: ['burns', 'positioning', 'contracture prevention', 'hand', 'safe position'],
  },
  {
    id: 'q035',
    domain: 'intervention',
    subdomain: 'Energy Conservation',
    stem: 'An OT is teaching energy conservation principles to a client with heart failure. Which of the following is a core energy conservation strategy?',
    type: 'mcq',
    options: [
      'A) Performing all tasks at a brisk pace to reduce total time spent on activities',
      'B) Clustering all heavy tasks in the morning when energy is highest',
      'C) Pacing activities, using rest breaks, and organizing the environment to reduce unnecessary effort',
      'D) Eliminating all leisure activities to reserve energy for self-care',
    ],
    correct: 2,
    rationale: 'Energy conservation (Work Simplification) principles include: plan ahead, organize environment (keep frequently used items accessible), pace activities by taking rest breaks before fatigued, prioritize tasks, and use proper body mechanics. Activities should be distributed across the day, not clustered. Leisure is important for quality of life and should not be eliminated. Performing tasks briskly increases cardiopulmonary demand.',
    difficulty: 1,
    tags: ['energy conservation', 'heart failure', 'fatigue', 'work simplification'],
  },
  {
    id: 'q036',
    domain: 'intervention',
    subdomain: 'Rheumatology',
    stem: 'A client with rheumatoid arthritis (RA) asks for advice on opening jars. Which joint protection principle does this situation primarily address?',
    type: 'mcq',
    options: [
      'A) Avoid positions that cause joint deformity — use ulnar deviation avoidance',
      'B) Use the largest joint available — use the palm to press rather than twisting with the fingers',
      'C) Maintain each joint in its optimal functional position throughout activity',
      'D) Avoid sustained muscle contraction — hold containers loosely',
    ],
    correct: 1,
    rationale: 'Joint protection principles for RA include: (1) use the largest/strongest joints available, (2) avoid positions that cause deformity (e.g., avoid ulnar deviation), (3) maintain optimal position, (4) avoid holding one position too long, (5) respect pain. For jar-opening, using a jar opener, pressing down on the lid with the palm (spreading force), or using two hands reduces stress on small finger joints and avoids ulnar-deviating forces.',
    difficulty: 2,
    tags: ['joint protection', 'RA', 'rheumatoid arthritis', 'ADL adaptation'],
  },
  {
    id: 'q037',
    domain: 'intervention',
    subdomain: 'Orthotic Intervention',
    stem: 'An OT fabricates a wrist immobilization orthosis for a client with carpal tunnel syndrome (CTS). In which position should the wrist be immobilized?',
    type: 'mcq',
    options: [
      'A) 30° wrist extension',
      'B) Neutral (0°) to slight extension (10–15°)',
      'C) 30° wrist flexion',
      'D) Full supination with the wrist in neutral',
    ],
    correct: 1,
    rationale: 'For carpal tunnel syndrome, wrist immobilization in neutral (0°) to slight extension (10–15°) is recommended. This position minimizes carpal tunnel pressure. Wrist flexion significantly increases carpal tunnel pressure and should be avoided. Wrist extension beyond 20° also increases pressure. The orthosis is typically worn at night and may also be worn during activities that aggravate symptoms.',
    difficulty: 2,
    tags: ['carpal tunnel', 'orthotic', 'wrist splint', 'median nerve'],
  },
  {
    id: 'q038',
    domain: 'intervention',
    subdomain: 'Hand Therapy',
    stem: 'A client is 3 weeks post repair of a zone II flexor tendon injury. The early active mobilization (EAM) protocol allows:',
    type: 'mcq',
    options: [
      'A) Full unrestricted active ROM of the digit',
      'B) Passive flexion and active extension only within a dorsal blocking orthosis',
      'C) Gentle active flexion and extension within a protective orthosis',
      'D) No movement — immobilization until 6 weeks post-surgery',
    ],
    correct: 2,
    rationale: 'Early active mobilization (EAM) protocols for zone II flexor tendon repairs (in the critical pulley zone) typically allow gentle active flexion and extension exercises within a dorsal blocking orthosis (DBO) beginning 24–48 hours post-surgery. This reduces adhesion formation while protecting the repair. The DBO limits wrist and MCP extension to prevent repair rupture. Passive flexion / active extension (Kleinert) and pure immobilization are older, less aggressive protocols.',
    difficulty: 3,
    tags: ['flexor tendon', 'zone II', 'hand therapy', 'EAM', 'orthotic'],
  },
  {
    id: 'q039',
    domain: 'intervention',
    subdomain: 'Neurological Rehabilitation',
    stem: 'A client with Parkinson\'s disease reports difficulty with handwriting, which has become very small. This is called:',
    type: 'mcq',
    options: [
      'A) Dysgraphia',
      'B) Micrographia',
      'C) Agraphia',
      'D) Bradykinesia of script',
    ],
    correct: 1,
    rationale: 'Micrographia is the clinical term for abnormally small handwriting, a classic feature of Parkinson\'s disease resulting from bradykinesia (slowness of movement) and hypokinesia (reduced amplitude of movement). OT interventions include LSVT BIG principles adapted to writing (exaggeratedly large movements), visual cues (guidelines, templates), and assistive technology if needed. Dysgraphia is a learning disability affecting writing; agraphia is inability to write due to neurological damage.',
    difficulty: 1,
    tags: ['Parkinson\'s', 'micrographia', 'handwriting', 'bradykinesia'],
  },
  {
    id: 'q040',
    domain: 'intervention',
    subdomain: 'Cognitive Rehabilitation',
    stem: 'An OT is working with a client with a moderate traumatic brain injury (TBI) who has poor prospective memory. Which compensatory strategy is MOST appropriate?',
    type: 'mcq',
    options: [
      'A) Memory drills to strengthen recall of past events',
      'B) External memory aid — a structured planner or smartphone reminder app',
      'C) Errorless learning for all new workplace tasks',
      'D) Internal memory strategy — method of loci or visual imagery',
    ],
    correct: 1,
    rationale: 'Prospective memory is the ability to remember to perform a planned action in the future (e.g., take medications at 8 am, bring a form to a meeting). External aids — calendars, planners, smartphone alarms, checklists — are the most effective evidence-based compensatory strategies for TBI-related prospective memory deficits. Internal mnemonic strategies require intact encoding and metacognition, which is often compromised in moderate TBI. Errorless learning addresses procedural/implicit memory for specific learned tasks.',
    difficulty: 2,
    tags: ['TBI', 'prospective memory', 'cognitive compensation', 'external aids'],
  },
  {
    id: 'q041',
    domain: 'intervention',
    subdomain: 'Pain Management',
    stem: 'In treating Complex Regional Pain Syndrome (CRPS) Type I of the upper extremity, which intervention approach has the BEST evidence as a foundation for recovery?',
    type: 'mcq',
    options: [
      'A) Complete immobilization to minimize pain and inflammation',
      'B) Graded exposure / desensitization combined with graded active use',
      'C) Aggressive passive joint mobilization to restore full ROM immediately',
      'D) Mirror visual feedback exclusively, with no physical contact with the affected limb',
    ],
    correct: 1,
    rationale: 'CRPS I management is graded and progressive: gentle desensitization (texture, temperature progression), mirror visual feedback (to cortical reorganization), graded motor imagery, and gradual graded return to active use of the extremity. Immobilization worsens CRPS by reinforcing disuse and cortical reorganization. Aggressive ROM increases pain and sympathetic activity. Mirror therapy is evidence-supported but is combined with other interventions, not used in isolation.',
    difficulty: 3,
    tags: ['CRPS', 'complex regional pain', 'desensitization', 'mirror therapy'],
  },
  {
    id: 'q042',
    domain: 'intervention',
    subdomain: 'Neurological Rehabilitation',
    stem: 'An OT is treating a client with multiple sclerosis (MS) who reports significant fatigue. Which intervention strategy is specifically supported by evidence for MS-related fatigue?',
    type: 'mcq',
    options: [
      'A) High-intensity aerobic exercise performed daily',
      'B) Fatigue management program including energy conservation, pacing, and activity modification',
      'C) Complete bed rest during fatigue episodes',
      'D) Cognitive behavioral therapy as a standalone intervention',
    ],
    correct: 1,
    rationale: 'MS-related fatigue (Lhermitte\'s fatigue, heat sensitivity) is managed through: energy conservation (prioritizing, planning, pacing), cooling strategies (cooling vests, air conditioning), activity modification, and structured fatigue management programs. Moderate aerobic exercise can be beneficial but must account for heat sensitivity and Uhthoff\'s phenomenon (symptom worsening with temperature increases). Complete rest perpetuates deconditioning. CBT alone without behavioral strategies is insufficient.',
    difficulty: 2,
    tags: ['multiple sclerosis', 'MS', 'fatigue management', 'energy conservation'],
  },
  {
    id: 'q043',
    domain: 'intervention',
    subdomain: 'Musculoskeletal',
    stem: 'An OT is providing body mechanics training to a client with low back pain. Which of the following is a correct principle to teach?',
    type: 'mcq',
    options: [
      'A) Bend at the waist to pick up objects to protect the knees',
      'B) Carry objects as far from the body as possible to engage the core muscles',
      'C) Pivot the whole body rather than twisting the trunk when turning',
      'D) Exhale when setting down a heavy object to reduce intra-abdominal pressure',
    ],
    correct: 2,
    rationale: 'Core body mechanics principles for low back pain: keep the load close to the body, maintain spinal neutral, bend knees and hips (not waist), engage the core (exhale/brace when lifting — increases intra-abdominal pressure), and PIVOT the whole body (feet move) instead of twisting the trunk when turning. Twisting under load is a major mechanism of lumbar disc injury. Carrying objects far from the body dramatically increases torque on the lumbar spine.',
    difficulty: 1,
    tags: ['low back pain', 'body mechanics', 'ergonomics', 'injury prevention'],
  },
  {
    id: 'q044',
    domain: 'intervention',
    subdomain: 'Orthotic Intervention',
    stem: 'A client is diagnosed with cubital tunnel syndrome (ulnar nerve compression at the elbow). What orthotic position is recommended?',
    type: 'mcq',
    options: [
      'A) Elbow in full extension to decompress the cubital tunnel',
      'B) Elbow at 30–45° flexion in a posterior elbow extension stop orthosis',
      'C) Elbow at 90° flexion to provide maximum nerve decompression',
      'D) Wrist in neutral — only the wrist is immobilized for cubital tunnel',
    ],
    correct: 1,
    rationale: 'Cubital tunnel syndrome involves compression of the ulnar nerve at the medial elbow. The nerve is most stretched/compressed in full elbow flexion. A nighttime elbow extension stop orthosis positions the elbow at 30–45° flexion, preventing the hyperflex positions that aggravate the nerve, while avoiding the full extension that limits function. Full extension decompresses but is poorly tolerated. 90° flexion is too close to the provocative position.',
    difficulty: 3,
    tags: ['cubital tunnel', 'ulnar nerve', 'elbow orthotic', 'hand therapy'],
  },
  {
    id: 'q045',
    domain: 'intervention',
    subdomain: 'Hand Pathology',
    stem: 'A 55-year-old client presents with trigger finger (stenosing tenosynovitis) of the right ring finger. When conservative OT management is appropriate, which orthosis is indicated?',
    type: 'mcq',
    options: [
      'A) MCP blocking orthosis holding the MCP in 0° extension',
      'B) Hand-based orthosis with the MCP joint in 10–15° flexion, blocking hyperextension',
      'C) A wrist immobilization orthosis in 20° extension',
      'D) Full finger extension splint covering the PIP and DIP joints only',
    ],
    correct: 1,
    rationale: 'Trigger finger orthosis intervention involves fabricating a hand-based MCP blocking orthosis that positions the MCP in slight flexion (10–15°) and restricts MCP hyperextension — hyperextension maximizes tendon excursion through the A1 pulley and is thought to perpetuate triggering. The goal is to limit provocative movements while allowing some function. Wrist orthoses without MCP control are not as directly effective for trigger finger.',
    difficulty: 3,
    tags: ['trigger finger', 'stenosing tenosynovitis', 'orthotic', 'hand therapy'],
  },
  {
    id: 'q046',
    domain: 'intervention',
    subdomain: 'Hand Pathology',
    stem: 'Swan neck deformity of a finger is characterized by:',
    type: 'mcq',
    options: [
      'A) PIP joint flexion with DIP joint hyperextension',
      'B) PIP joint hyperextension with DIP joint flexion',
      'C) MCP hyperextension with PIP and DIP flexion ("intrinsic minus")',
      'D) MCP flexion with PIP and DIP extension',
    ],
    correct: 1,
    rationale: 'Swan neck deformity = PIP hyperextension + DIP flexion. It results from imbalance of intrinsic muscles relative to the long extensor mechanism (typically seen in RA). This is the opposite of boutonniere deformity. Mnemonic: swan necks arch upward (PIP up = hyperextension), then bend down (DIP down = flexion). Orthotic management uses a figure-of-8 ring orthosis to limit PIP hyperextension while allowing full flexion.',
    difficulty: 2,
    tags: ['swan neck', 'finger deformity', 'RA', 'hand therapy'],
  },
  {
    id: 'q047',
    domain: 'intervention',
    subdomain: 'Hand Pathology',
    stem: 'A boutonniere deformity of the finger is characterized by:',
    type: 'mcq',
    options: [
      'A) PIP hyperextension with DIP flexion',
      'B) PIP flexion with DIP hyperextension',
      'C) MCP hyperextension with all IP joints in flexion',
      'D) Lateral deviation of the PIP joint with fusiform swelling',
    ],
    correct: 1,
    rationale: 'Boutonniere deformity = PIP flexion + DIP hyperextension. It results from disruption of the central slip of the extensor tendon (the head pokes through the buttonhole), causing the lateral bands to migrate volarly. The extensor force is then directed entirely at the DIP, causing hyperextension. OT orthotic management: position the PIP in extension while leaving the DIP free to flex (promotes DIP active flexion and lateral band repositioning).',
    difficulty: 2,
    tags: ['boutonniere', 'finger deformity', 'central slip', 'hand therapy'],
  },
  {
    id: 'q048',
    domain: 'intervention',
    subdomain: 'Peripheral Nerve Injury',
    stem: 'A client has a low ulnar nerve injury. Which functional deficit would the OT MOST expect to find during evaluation?',
    type: 'mcq',
    options: [
      'A) Weakness of wrist extension and inability to extend the fingers at the PIP joints',
      'B) Loss of opposition of the thumb and weakness of the thenar muscles',
      'C) Weakness of intrinsic hand muscles, loss of 5th finger abduction, and weak lateral pinch',
      'D) Wrist drop and loss of MCP extension in all fingers',
    ],
    correct: 2,
    rationale: 'Low ulnar nerve injury (distal to wrist, at or distal to Guyon\'s canal) affects: hypothenar muscles (5th finger abduction, opposition of little finger), interossei (finger abduction/adduction), ulnar two lumbricals (ring and small finger MCP flexion + IP extension), adductor pollicis (lateral/key pinch), and flexor digiti minimi. Results: weak key pinch, clawing of ring and small fingers, Froment\'s sign. Wrist drop = radial nerve; thenar weakness = median nerve.',
    difficulty: 2,
    tags: ['ulnar nerve', 'peripheral nerve', 'hand therapy', 'intrinsic muscles'],
  },
  {
    id: 'q049',
    domain: 'intervention',
    subdomain: 'Peripheral Nerve Injury',
    stem: 'A client with a radial nerve injury at the level of the posterior interosseous nerve (PIN) would have:',
    type: 'mcq',
    options: [
      'A) Wrist drop with inability to extend the wrist',
      'B) Full wrist extension preserved, but weakness/loss of finger and thumb extension',
      'C) Loss of sensation over the dorsal hand and thumb web space only',
      'D) Intrinsic muscle paralysis with clawing of ring and small fingers',
    ],
    correct: 1,
    rationale: 'The PIN is the deep motor branch of the radial nerve. It innervates the extrinsic finger and thumb extensors (excluding the ECRB, which is innervated proximal to the PIN). A pure PIN injury spares wrist extension (driven by ECRL and ECRB) but causes finger/thumb extension weakness. High radial nerve injuries (above the elbow) cause classic wrist drop. PIN injuries do not affect sensation, as the superficial radial nerve carries sensory fibers.',
    difficulty: 3,
    tags: ['radial nerve', 'PIN', 'peripheral nerve', 'hand therapy'],
  },
  {
    id: 'q050',
    domain: 'intervention',
    subdomain: 'Neurological Rehabilitation',
    stem: 'An OT is training a client with right hemiplegia to dress independently. Which dressing technique is recommended?',
    type: 'mcq',
    options: [
      'A) Dress the uninvolved (left) side first; undress the involved (right) side first',
      'B) Dress the involved (right) side first; undress the uninvolved (left) side first',
      'C) Always dress and undress the uninvolved side first to minimize time in the task',
      'D) Dress and undress from the head downward in anatomical sequence',
    ],
    correct: 1,
    rationale: 'The standard hemiplegia dressing rule: Dress the INVOLVED (weaker) side FIRST; Undress the INVOLVED (weaker) side LAST. This is because the affected arm/leg has restricted ROM and cannot be easily maneuvered through garment openings. By dressing it first, the garment can be positioned before the stronger arm or leg is inserted. Mnemonic: "Dress the worst first; undress the best first."',
    difficulty: 1,
    tags: ['hemiplegia', 'stroke', 'dressing', 'ADL', 'compensation'],
  },

  // ─────────────────────────────────────────────
  //  INTERVENTION — Low Vision & Positioning
  // ─────────────────────────────────────────────
  {
    id: 'q051',
    domain: 'intervention',
    subdomain: 'Low Vision',
    stem: 'A client with macular degeneration has lost central vision. The OT should teach which compensatory strategy for reading?',
    type: 'mcq',
    options: [
      'A) Eccentric viewing — using the peripheral retina to look slightly away from text',
      'B) Magnification lenses placed directly over the macula',
      'C) Reducing room lighting to decrease glare on the page',
      'D) Using a typoscope to eliminate peripheral distractors',
    ],
    correct: 0,
    rationale: 'Macular degeneration destroys central (foveal) vision. Eccentric viewing trains the client to use an intact peripheral retinal area (a preferred retinal locus, or PRL) by looking slightly off-center so that text falls on the functional retinal area. High-contrast reading materials, adequate lighting, magnification, and typoscopes (high-contrast reading guides) supplement this approach. Reducing lighting worsens reading for most low-vision clients who actually need more light.',
    difficulty: 2,
    tags: ['macular degeneration', 'low vision', 'eccentric viewing', 'visual impairment'],
  },
  {
    id: 'q052',
    domain: 'intervention',
    subdomain: 'Dysphagia',
    stem: 'A client post-brainstem stroke has dysphagia with aspiration risk. The OT should recommend which positioning strategy during meals?',
    type: 'mcq',
    options: [
      'A) Semi-reclined at 30–45° with neck in hyperextension',
      'B) Upright at 90° with neck in slight chin tuck',
      'C) Side-lying on the unaffected side to use gravity for bolus transport',
      'D) Prone positioning to reduce aspiration of liquids',
    ],
    correct: 1,
    rationale: 'For dysphagia management, the evidence-based positioning is: seat the client as upright as possible (90°), with hips at 90°, and a slight chin tuck (chin-down) position. The chin tuck narrows the laryngeal inlet and widens the valleculae, directing the bolus toward the esophagus and reducing aspiration risk. Hyperextension of the neck opens the airway and increases aspiration risk. The 30–45° recline with neck extension is contraindicated. Side-lying is used only in specific cases with known unilateral pharyngeal weakness.',
    difficulty: 2,
    tags: ['dysphagia', 'aspiration', 'chin tuck', 'stroke', 'positioning'],
  },

  // ─────────────────────────────────────────────
  //  PEDIATRIC PRACTICE  (Q053–Q065)
  // ─────────────────────────────────────────────
  {
    id: 'q053',
    domain: 'pediatrics',
    subdomain: 'Sensory Processing',
    stem: 'A sensory diet is best described as:',
    type: 'mcq',
    options: [
      'A) A nutritional plan to reduce food sensitivities in children with autism',
      'B) A schedule of targeted sensory activities individualized to meet a child\'s arousal and sensory processing needs throughout the day',
      'C) A systematic desensitization program using only tactile stimulation',
      'D) A list of restricted sensory environments that a child must avoid',
    ],
    correct: 1,
    rationale: 'A sensory diet (Wilbarger) is a personalized, scheduled plan of sensory activities and accommodations designed to regulate a child\'s central nervous system arousal level. It includes alerting, organizing, and calming sensory inputs (proprioception, vestibular, deep pressure, etc.) timed throughout the day. It is individualized during evaluation and implemented across settings by the child, family, and school staff. It is NOT about food or a list of restrictions.',
    difficulty: 1,
    tags: ['sensory diet', 'Wilbarger', 'sensory processing', 'pediatrics', 'autism'],
  },
  {
    id: 'q054',
    domain: 'pediatrics',
    subdomain: 'Handwriting',
    stem: 'A 6-year-old shows a quadrupod (4-finger) pencil grasp. This is BEST characterized as:',
    type: 'mcq',
    options: [
      'A) An immature grasp that should be retrained to a dynamic tripod immediately',
      'B) A functional non-standard grasp that may or may not require intervention depending on legibility and efficiency',
      'C) Pathological — always associated with developmental coordination disorder',
      'D) The developmentally expected grasp for a 6-year-old',
    ],
    correct: 1,
    rationale: 'Current evidence (Schwellnus et al., Schneck et al.) suggests that non-standard grasps (including quadrupod) are not automatically dysfunctional. Intervention should be guided by functional outcomes: legibility, speed, endurance, and discomfort. If writing is legible and efficient with no pain, grasp retraining may not be necessary or worthwhile. OTs evaluate the functional impact, not just the grasp pattern. Forcing retraining of an established grasp can reduce function.',
    difficulty: 2,
    tags: ['pencil grasp', 'handwriting', 'pediatrics', 'evidence-based'],
  },
  {
    id: 'q055',
    domain: 'pediatrics',
    subdomain: 'Autism Spectrum',
    stem: 'An OT is working with a 5-year-old with autism spectrum disorder (ASD) who has difficulty transitioning between activities. Which environmental modification would MOST effectively support transitions?',
    type: 'mcq',
    options: [
      'A) Verbal reminders delivered 30 seconds before transition time',
      'B) A visual schedule with pictures showing the daily sequence of activities',
      'C) Physical guidance through each transition to reduce anxiety',
      'D) Reducing or eliminating transitions to minimize stress',
    ],
    correct: 1,
    rationale: 'Visual schedules use pictures, symbols, or photographs to represent the sequence of daily activities and schedule changes. They are a Tier 1 evidence-based practice for autism (National Clearinghouse on Autism Evidence and Practice) that supports predictability, reduces transition anxiety, builds independence, and supports executive function. Visual modality is often a relative strength in ASD. Short verbal reminders can supplement but not replace visual supports.',
    difficulty: 1,
    tags: ['autism', 'ASD', 'visual schedule', 'transitions', 'evidence-based'],
  },
  {
    id: 'q056',
    domain: 'pediatrics',
    subdomain: 'Neurological Conditions',
    stem: 'An OT using NDT (Bobath) handling techniques with a child with spastic diplegic cerebral palsy applies deep pressure and elongation to the trunk while the child is in a standing frame. What is the PRIMARY goal of this handling?',
    type: 'mcq',
    options: [
      'A) Strengthen trunk extensors through resistance training',
      'B) Facilitate normal postural alignment and reduce extensor hypertonicity',
      'C) Stretch tight hamstring and hip flexor muscles statically',
      'D) Improve the child\'s endurance through prolonged weight-bearing',
    ],
    correct: 1,
    rationale: 'NDT/Bobath handling focuses on: normalizing postural tone, facilitating alignment and automatic postural reactions, and preparing the body for functional movement. In spastic diplegia, the lower limb extensor pattern (scissoring, toe-walking, hip adduction) predominates. Deep trunk pressure and elongation inhibit excessive extensor hypertonicity and facilitate a more neutral, aligned trunk and pelvis, allowing more normal lower extremity alignment. The primary aim is normalizing tone and facilitating alignment, not passive stretching or strengthening alone.',
    difficulty: 2,
    tags: ['NDT', 'cerebral palsy', 'spastic diplegia', 'postural control', 'pediatrics'],
  },
  {
    id: 'q057',
    domain: 'pediatrics',
    subdomain: 'Self-Care Training',
    stem: 'An OT is teaching a child with intellectual disability to button a shirt using backward chaining. Which of the following correctly describes this technique?',
    type: 'mcq',
    options: [
      'A) The therapist performs all steps; the child watches and then imitates the whole task',
      'B) The child practices only the FIRST step; the therapist completes remaining steps',
      'C) The child learns and performs the LAST step first, progressing backward to the first step as each is mastered',
      'D) The task is broken into equal parts practiced simultaneously across multiple trials',
    ],
    correct: 2,
    rationale: 'Backward chaining starts with the final step — the child performs the last step of the task while the therapist completes all preceding steps. Once the final step is mastered, the second-to-last is added, and so on, until the child completes the entire sequence. Backward chaining provides immediate success and reinforcement (completing the task) at the end of each trial, which increases motivation and learning. It differs from forward chaining (starting with step 1) and total task presentation.',
    difficulty: 1,
    tags: ['backward chaining', 'self-care', 'intellectual disability', 'task training'],
  },
  {
    id: 'q058',
    domain: 'pediatrics',
    subdomain: 'Sensory Processing',
    stem: 'A child who consistently seeks out intense proprioceptive input — crashing into furniture, jumping from heights, seeking bear hugs — is demonstrating which sensory processing pattern?',
    type: 'mcq',
    options: [
      'A) Sensory modulation disorder — hypersensitivity',
      'B) Sensory craving — hyposensitivity / underresponsive with high sensory-seeking behavior',
      'C) Dyspraxia secondary to poor somatosensory processing',
      'D) Gravitational insecurity with vestibular overresponsivity',
    ],
    correct: 1,
    rationale: 'Sensory seeking (craving) describes a child with a high sensory threshold (underresponsive) who actively seeks out intense sensory input to meet their neurological needs. These children often appear impulsive, restless, or "driven by a motor." Intervention includes providing regular, intense proprioceptive input (heavy work) through a sensory diet. This is distinct from hypersensitivity (high response to low input), dyspraxia (motor planning disorder), and gravitational insecurity (vestibular overresponsivity to movement).',
    difficulty: 2,
    tags: ['sensory seeking', 'proprioception', 'sensory processing', 'pediatrics'],
  },
  {
    id: 'q059',
    domain: 'pediatrics',
    subdomain: 'School-Based Practice',
    stem: 'Under IDEA (Individuals with Disabilities Education Act), school-based OT services must be provided in the Least Restrictive Environment (LRE). Which service delivery model BEST aligns with LRE principles?',
    type: 'mcq',
    options: [
      'A) Pulling the student out to a separate OT room for all therapy sessions',
      'B) Embedding OT goals and strategies into the regular classroom and daily activities as much as possible',
      'C) Providing OT services only to students in self-contained special education classrooms',
      'D) Completing all OT evaluation and documentation outside student class time',
    ],
    correct: 1,
    rationale: 'IDEA mandates that students with disabilities receive education (and related services including OT) in the least restrictive environment — to the maximum extent appropriate alongside non-disabled peers. An integrated/consultative model where OT strategies are embedded in the classroom and natural routines is most aligned with LRE. Pull-out therapy is used when classroom-based services cannot fulfill the student\'s educational needs. Services are educationally relevant and support participation in the curriculum.',
    difficulty: 1,
    tags: ['IDEA', 'LRE', 'school-based OT', 'inclusive education'],
  },
  {
    id: 'q060',
    domain: 'pediatrics',
    subdomain: 'Developmental Milestones',
    stem: 'At what age would a typically developing child be expected to cut paper along a straight line with scissors?',
    type: 'mcq',
    options: [
      'A) 2 years',
      'B) 3.5–4 years',
      'C) 5–5.5 years',
      'D) 6–7 years',
    ],
    correct: 1,
    rationale: 'Scissor skill development: random snipping (2.5–3 yrs) → cutting across paper (3–3.5 yrs) → cutting a straight line (3.5–4 yrs) → cutting simple shapes (4–4.5 yrs) → cutting complex shapes/curves (~5–6 yrs). At 3.5–4 years, cutting along a straight line is a developmentally expected milestone. Children who cannot cut a straight line by age 4.5 may warrant further evaluation of bilateral coordination, motor planning, or hand strength.',
    difficulty: 1,
    tags: ['scissors', 'fine motor', 'developmental milestones', 'pediatrics'],
  },
  {
    id: 'q061',
    domain: 'pediatrics',
    subdomain: 'Sensory Processing',
    stem: 'Which type of sensory input is typically considered the MOST organizing and calming in sensory integration intervention?',
    type: 'mcq',
    options: [
      'A) Unpredictable vestibular input (spinning, rocking)',
      'B) Heavy work / proprioceptive input (pushing, pulling, carrying weighted objects)',
      'C) High-frequency auditory input (music, loud noise)',
      'D) Light touch applied unexpectedly to the skin',
    ],
    correct: 1,
    rationale: 'Proprioceptive / heavy work input (joint compression, traction, carrying weighted items, pulling, pushing) is considered the most reliably organizing and calming sensory input in SI theory. It helps regulate arousal and is widely used in sensory diets. Vestibular input is powerful and alerting or calming depending on type, but unpredictable vestibular input can be dysregulating. Unexpected light touch is alerting and often aversive for sensory-sensitive children.',
    difficulty: 1,
    tags: ['proprioception', 'heavy work', 'sensory integration', 'calming', 'regulation'],
  },
  {
    id: 'q062',
    domain: 'pediatrics',
    subdomain: 'Vestibular System',
    stem: 'A child demonstrates gravitational insecurity. Which behavior is MOST characteristic?',
    type: 'mcq',
    options: [
      'A) Actively seeking spinning on a swivel chair and rolling down hills',
      'B) Fear and anxiety when feet leave the ground or during normal movement',
      'C) Falling frequently due to poor balance on unstable surfaces',
      'D) Difficulty coordinating bilateral arm and leg movements in swimming',
    ],
    correct: 1,
    rationale: 'Gravitational insecurity is an overresponsivity to vestibular input — particularly changing head position, having feet off the ground, and movement. Children show fear or anxiety disproportionate to actual risk during activities like swings, stairs, or playground equipment. They often avoid spontaneous movement. It differs from poor balance (a motor/vestibular processing deficit without fear) or sensory seeking (underresponsivity). Treatment uses a sensory integrative approach with graded, child-controlled movement experiences.',
    difficulty: 2,
    tags: ['gravitational insecurity', 'vestibular', 'sensory processing', 'pediatrics'],
  },
  {
    id: 'q063',
    domain: 'pediatrics',
    subdomain: 'Autism Spectrum',
    stem: 'PECS (Picture Exchange Communication System) is used in OT/education settings for children with ASD primarily to:',
    type: 'mcq',
    options: [
      'A) Teach academic skills through picture-based instruction',
      'B) Develop functional communication by exchanging picture symbols to make requests',
      'C) Provide visual supports for sensory regulation throughout the school day',
      'D) Assess communication level using structured picture-matching tasks',
    ],
    correct: 1,
    rationale: 'PECS is an augmentative and alternative communication (AAC) system developed by Frost and Bondy for individuals with autism who are minimally verbal. Children learn to initiate communication by handing a picture card to a communication partner to make requests, comments, or greetings. PECS progresses through 6 phases. It is implemented by SLPs, OTs (in occupation-focused activities), and educators. It is distinct from visual schedules (which support routine/sequencing) and academic picture cards.',
    difficulty: 1,
    tags: ['PECS', 'autism', 'AAC', 'communication', 'school-based'],
  },

  // ─────────────────────────────────────────────
  //  MENTAL HEALTH  (Q064–Q068)
  // ─────────────────────────────────────────────
  {
    id: 'q064',
    domain: 'mental_health',
    subdomain: 'Allen Cognitive Model',
    stem: 'A client functioning at Allen Cognitive Level 3 (Manual Actions) can typically perform:',
    type: 'mcq',
    options: [
      'A) Complex multi-step tasks with written instructions independently',
      'B) Simple, repetitive tasks with hands-on demonstration and cueing',
      'C) Basic grooming with full physical assistance only',
      'D) Familiar well-established routines with verbal cueing only',
    ],
    correct: 1,
    rationale: 'Allen Cognitive Level 3 (Manual Actions) corresponds to repetitive, rote motor actions — clients can follow hands-on demonstrations and perform repetitive tasks but cannot problem-solve or sequence multiple steps. They attend to tactile cues. Supervision and a structured environment are required. Level 4 (Goal-Directed Activity): follows simple step-by-step instructions with visible errors noticed. Level 5: can learn new procedures through trial and error. Level 6: normal cognition.',
    difficulty: 2,
    tags: ['Allen', 'cognitive level 3', 'mental health', 'functional cognition'],
  },
  {
    id: 'q065',
    domain: 'mental_health',
    subdomain: 'Recovery Model',
    stem: 'The Recovery Model of mental health services is BEST characterized by:',
    type: 'mcq',
    options: [
      'A) Eliminating all symptoms before the client returns to community living',
      'B) A focus on hope, self-determination, and building a meaningful life regardless of symptom status',
      'C) Structured behavioral management by the treatment team to ensure medication compliance',
      'D) Hospitalization as the primary treatment setting for psychiatric rehabilitation',
    ],
    correct: 1,
    rationale: 'The Recovery Model (Anthony, 1993; SAMHSA) emphasizes: hope, self-determination, person-directed goals, community integration, and building a meaningful and satisfying life even with ongoing mental health challenges. Recovery does not mean cure or the absence of symptoms. OT supports recovery through occupation-based interventions that address roles, habits, routines, and community participation. This contrasts with the medical model\'s focus on symptom elimination as a prerequisite to participation.',
    difficulty: 1,
    tags: ['recovery model', 'mental health', 'SAMHSA', 'self-determination'],
  },
  {
    id: 'q066',
    domain: 'mental_health',
    subdomain: 'Group Facilitation',
    stem: 'An OT is leading a task group with clients on an inpatient psychiatric unit. The PRIMARY distinction of a task group over a verbal/psychotherapy group is:',
    type: 'mcq',
    options: [
      'A) Task groups are longer in duration and require more structured assessment',
      'B) Task groups use doing — purposeful activity — as the primary medium for therapeutic change',
      'C) Task groups focus exclusively on work-related skills and vocational readiness',
      'D) Task groups are led only by occupational therapists, not other disciplines',
    ],
    correct: 1,
    rationale: 'Task groups (Fidler\'s task-oriented group; OT groups) use purposeful activity and "doing" as the medium for achieving therapeutic goals. The activity itself provides a here-and-now experience that elicits authentic behavior, allowing the OT to observe and address interpersonal, cognitive, and performance skill deficits in context. Verbal groups rely primarily on discussion. Task groups can be used for many functional goals beyond work skills and can focus on ADL, leisure, social skills, or creative expression.',
    difficulty: 1,
    tags: ['task group', 'group intervention', 'inpatient psychiatry', 'purposeful activity'],
  },
  {
    id: 'q067',
    domain: 'mental_health',
    subdomain: 'Cognitive Approaches',
    stem: 'An OT is using a Cognitive Behavioral Therapy (CBT)-informed approach with a client who has depression and avoids all outings due to catastrophic thinking. The FIRST step in CBT is to:',
    type: 'mcq',
    options: [
      'A) Immediately create a behavioral activation schedule with gradual exposure to avoided activities',
      'B) Identify and collaboratively examine the client\'s negative automatic thoughts linked to the avoided behavior',
      'C) Teach deep breathing and progressive muscle relaxation to manage anxiety',
      'D) Explore early childhood experiences that may have caused the avoidance pattern',
    ],
    correct: 1,
    rationale: 'The cognitive model (Beck) identifies automatic thoughts as the first target: the therapist and client collaboratively identify negative automatic thoughts (e.g., "Something terrible will happen if I go outside"). These are examined for cognitive distortions (catastrophizing, overgeneralization) before behavioral interventions are introduced. Behavioral activation (A) is an important CBT component but follows or is integrated with cognitive restructuring. Deep breathing = relaxation, not CBT per se. Early childhood exploration is psychodynamic, not CBT.',
    difficulty: 2,
    tags: ['CBT', 'depression', 'automatic thoughts', 'cognitive restructuring'],
  },
  {
    id: 'q068',
    domain: 'mental_health',
    subdomain: 'PTSD',
    stem: 'An OT is working with a combat veteran with PTSD focusing on sleep hygiene. Which intervention has the strongest evidence for PTSD-related sleep disturbance in an occupational therapy context?',
    type: 'mcq',
    options: [
      'A) Long-term use of sleep medication to ensure uninterrupted sleep',
      'B) Sleep hygiene education combined with relaxation training and stimulus control strategies',
      'C) Eliminating all nighttime activity and maintaining bed rest for 10+ hours',
      'D) Exposure therapy during bedtime hours to process traumatic memories',
    ],
    correct: 1,
    rationale: 'OT sleep hygiene interventions for PTSD include: consistent sleep/wake schedule (stimulus control — bed for sleep only), relaxation training (progressive muscle relaxation, diaphragmatic breathing), worry management strategies, wind-down routines, optimizing the sleep environment, and sleep restriction when indicated. This aligns with CBT-I (Cognitive Behavioral Therapy for Insomnia), which has a strong evidence base. Long-term sleep medication use carries dependence risks. Total bed rest = sleep compression, not therapeutic. Trauma processing during bedtime is inadvisable.',
    difficulty: 2,
    tags: ['PTSD', 'sleep hygiene', 'veteran', 'CBT-I', 'occupational performance'],
  },

  // ─────────────────────────────────────────────
  //  PROFESSIONAL PRACTICE  (Q069–Q075)
  // ─────────────────────────────────────────────
  {
    id: 'q069',
    domain: 'professional',
    subdomain: 'Supervision',
    stem: 'According to AOTA standards, which statement BEST describes the OTR\'s supervisory role over an OTA?',
    type: 'mcq',
    options: [
      'A) The OTR must be physically present during every treatment session the OTA provides',
      'B) The OTR is responsible for all evaluation, goal setting, and treatment planning; the OTA implements intervention under appropriate OTR supervision and collaboration',
      'C) An OTA may independently evaluate clients, set goals, and discharge without OTR review in any setting after 5 years of experience',
      'D) Supervision levels are determined solely by the OTA\'s preference, not by setting or complexity',
    ],
    correct: 1,
    rationale: 'AOTA (2020 Standards of Practice) and state laws specify: the OTR is responsible for evaluation, occupational profile, interpretation of findings, intervention planning, and discharge decisions. The OTA contributes data and implements the plan under OTR supervision. Supervision levels (routine to general) depend on OTA competency, setting complexity, and state regulation — not solely the OTA\'s preference or years of experience. Physical presence at every session is not required but regular communication and collaboration are.',
    difficulty: 2,
    tags: ['OTA', 'supervision', 'OTR', 'scope of practice', 'AOTA standards'],
  },
  {
    id: 'q070',
    domain: 'professional',
    subdomain: 'Legal and Ethical',
    stem: 'A family member calls the rehabilitation unit asking for information about their adult relative\'s progress. According to HIPAA, the OT should:',
    type: 'mcq',
    options: [
      'A) Freely share all clinical information since the caller is a family member',
      'B) Verify patient consent and authorization before disclosing any PHI to the family member',
      'C) Immediately transfer the call to the charge nurse who handles all HIPAA matters',
      'D) Decline to confirm whether the person is even a patient at the facility',
    ],
    correct: 1,
    rationale: 'HIPAA (The Health Insurance Portability and Accountability Act) requires a covered entity to obtain patient authorization before disclosing protected health information (PHI) to third parties, including family members, unless: (1) the patient has designated the family member as an authorized representative, (2) the patient is present and consents verbally, or (3) it is necessary for the patient\'s care and the patient lacks capacity. Family relationship alone does not grant automatic access to PHI.',
    difficulty: 1,
    tags: ['HIPAA', 'confidentiality', 'PHI', 'legal', 'professional ethics'],
  },
  {
    id: 'q071',
    domain: 'professional',
    subdomain: 'Ethics',
    stem: 'An OT notices a supervisor billing for services that were not provided. The OT\'s MOST ethically appropriate first action is to:',
    type: 'mcq',
    options: [
      'A) Ignore the situation to avoid conflict with the supervisor',
      'B) Immediately contact CMS (Centers for Medicare & Medicaid Services) without speaking to the supervisor',
      'C) Document concerns internally and address the supervisor or facility compliance officer through established channels',
      'D) Resign immediately to avoid legal liability',
    ],
    correct: 2,
    rationale: 'Healthcare fraud (billing for services not rendered) is a federal crime. AOTA\'s Code of Ethics (Principle 6: Justice) obligates OTs to report suspected violations. Best practice: follow institutional compliance reporting channels first (document, report to compliance officer or ethics committee), then escalate externally if internal reporting fails. Immediate action with external agencies (e.g., CMS fraud hotline) is appropriate if internal channels are exhausted or if there is retaliation. Ignoring fraud violates professional obligation.',
    difficulty: 2,
    tags: ['fraud', 'billing', 'ethics', 'AOTA Code of Ethics', 'compliance'],
  },
  {
    id: 'q072',
    domain: 'professional',
    subdomain: 'Reimbursement',
    stem: 'Under Medicare Part B, OT services in an outpatient clinic are subject to:',
    type: 'mcq',
    options: [
      'A) No annual caps — OT services are unlimited under Medicare Part B',
      'B) A therapy cap with an exception process requiring medical necessity justification',
      'C) Payment only for restoration of function, not maintenance therapy',
      'D) Coverage only when the client is also receiving physical therapy',
    ],
    correct: 1,
    rationale: 'Medicare Part B covers OT in outpatient settings. Historically, a therapy cap applied (combined PT/SLP cap, and a separate OT cap) with a KX modifier exception process for medically necessary services above the cap. The Bipartisan Budget Act 2018 eliminated hard caps but retained the KX modifier requirement for claims above the threshold, requiring documentation justifying medical necessity. Maintenance therapy may also be covered (Jimmo v. Sebelius, 2013 CMS policy update). OT coverage is independent of PT.',
    difficulty: 2,
    tags: ['Medicare Part B', 'therapy cap', 'reimbursement', 'KX modifier'],
  },
  {
    id: 'q073',
    domain: 'professional',
    subdomain: 'Goal Writing',
    stem: 'Which of the following is a well-written SMART OT goal?',
    type: 'mcq',
    options: [
      'A) "Client will improve dressing skills."',
      'B) "Client will demonstrate improved upper extremity strength and coordination."',
      'C) "Client will don a pullover shirt with minimal assistance of one person in ≤5 minutes, in 3 of 4 trials, within 4 weeks."',
      'D) "Client will benefit from continued OT intervention to optimize functional independence."',
    ],
    correct: 2,
    rationale: 'SMART goals are Specific, Measurable, Achievable, Relevant, and Time-bound. Option C specifies the task (pullover shirt), performance level (minimal assistance of one person), measurability (≤5 minutes, 3/4 trials), and a timeframe (4 weeks). Options A and B lack measurable criteria and timeframes. Option D is a statement of clinical justification, not a measurable outcome goal. Well-written OT goals directly link to functional performance and enable objective progress monitoring.',
    difficulty: 1,
    tags: ['SMART goals', 'documentation', 'goal writing', 'professional practice'],
  },
  {
    id: 'q074',
    domain: 'professional',
    subdomain: 'Cultural Competence',
    stem: 'A client from a collectivist cultural background defers all medical decisions to the eldest son rather than making independent choices. The OT should:',
    type: 'mcq',
    options: [
      'A) Insist that the client make all decisions independently to uphold autonomy',
      'B) Acknowledge and respect that the client\'s values may involve family-centered decision-making',
      'C) Document that the client lacks decision-making capacity due to deference behavior',
      'D) Consult the ethics committee immediately due to potential elder abuse',
    ],
    correct: 1,
    rationale: 'Cultural competence requires recognizing that Western medical ethics prioritizes individual autonomy, but many cultures (e.g., East Asian, Latin American, Middle Eastern, many immigrant communities) hold collectivist values where family-centered decision-making is the norm and is congruent with the client\'s own values. The OT should explore the client\'s preferences, ensure the client is not being coerced, and respect cultural values as part of client-centered care. Labeling this as incapacity or elder abuse without evidence is ethically inappropriate.',
    difficulty: 2,
    tags: ['cultural competence', 'autonomy', 'collectivism', 'ethics', 'client-centered'],
  },
  {
    id: 'q075',
    domain: 'professional',
    subdomain: 'Telehealth',
    stem: 'An OT provides telehealth services to a rural client who cannot travel. Which ethical obligation is MOST important to address before initiating telehealth OT services?',
    type: 'mcq',
    options: [
      'A) Ensuring the client has the fastest available internet connection',
      'B) Obtaining informed consent specific to telehealth, including risks, benefits, and platform security',
      'C) Requiring the client to complete a home safety checklist before the first session',
      'D) Verifying that the client agrees to record all sessions for quality assurance',
    ],
    correct: 1,
    rationale: 'Before initiating telehealth OT, the OT must obtain informed consent that addresses: the nature of telehealth, data security and confidentiality risks, limitations compared to in-person care, scope of services, emergency protocols, billing/coverage, and right to discontinue. AOTA\'s telehealth position paper and state licensing boards require telehealth-specific consent. While technology access is practical, and home safety is relevant, informed consent is the overriding ethical and legal obligation before service begins.',
    difficulty: 2,
    tags: ['telehealth', 'informed consent', 'ethics', 'AOTA', 'professional practice'],
  },
];

// Total question count and domain distribution
const QUESTION_STATS = {
  total: QUESTIONS.length,
  byDomain: DOMAINS.reduce((acc, d) => {
    acc[d.id] = QUESTIONS.filter(q => q.domain === d.id).length;
    return acc;
  }, {}),
};
